name: Deploy dev
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Lint and test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.19
          cache: yarn
      - run: yarn
      - run: yarn nx run web:build
      - run: yarn sst deploy --stage dev
