name: Lint and test
on: [push]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.19
          cache: yarn
      - run: yarn
      - run: yarn nx affected:lint
      - run: yarn nx affected:test
