name: CI

on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules-
      - run: yarn --prefer-offline
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
      - run: yarn nx affected:lint
      - run: yarn nx affected:test
      - run: yarn nx affected:e2e
  deploy-develop:
    name: deploy[develop]
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/develop'
    environment: develop
    env:
      SST_TELEMETRY_DISABLED: 1
      AMAZON_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AMAZON_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules-
      - run: yarn --prefer-offline
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
      - run: yarn nx run web:build
      - run: yarn sst deploy --stage develop
  deploy-main:
    name: deploy[main]
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    environment: main
    env:
      SST_TELEMETRY_DISABLED: 1
      AMAZON_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AMAZON_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules-
      - run: yarn --prefer-offline
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
      - run: yarn nx run web:build
      - run: yarn sst deploy --stage main
