name: CI

on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - run: yarn
      - run: yarn nx affected:lint
      - run: yarn nx affected:test
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    environment: dev
    env:
      SST_TELEMETRY_DISABLED: 1
      AMAZON_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AMAZON_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - run: yarn
      - run: yarn nx run web:build
      - run: yarn sst deploy --stage dev
